const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  //admin
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",
  FETCH_GENDER_START: "FETCH_GENDER_START",

  FETCH_POSITION_SUCCESS: "USER_POSITION_SUCCESS",
  FETCH_POSITION_FAIDED: "USER_POSITION_FAIL",

  FETCH_ROLE_SUCCESS: "USER_ROLE_SUCCESS",
  FETCH_ROLE_FAIDED: "USER_ROLE_FAIL",

  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAIDED: "SAVE_USER_FAIL",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
});

export default actionTypes;
