const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  //admin
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",
  FETCH_GENDER_START: "FETCH_GENDER_START",

  FETCH_POSITION_SUCCESS: "USER_POSITION_SUCCESS",
  FETCH_POSITION_FAIDED: "USER_POSITION_FAIL",

  FETCH_ROLE_SUCCESS: "USER_ROLE_SUCCESS",
  FETCH_ROLE_FAIDED: "USER_ROLE_FAIL",

  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAIDED: "SAVE_USER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIDED: "EDIT_USER_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIDED: "DELETE_USER_FAIDED",

  FETCH_ALL_USERS_SUCCESS: "USER_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAIDED: "USER_ALL_USERS_FAIL",

  FETCH_TOP_DOCTORS_SUCCESS: "USER_TOP_DOCTORS_SUCCESS",
  FETCH_TOP_DOCTORS_FAIDED: "USER_TOP_DOCTORS_FAIL",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
});

export default actionTypes;
